const cfg=window.APP_CONFIG||{};
const authState={session:null,mode:cfg.mode||'demo'};
window.autoZapAuth=authState;
window.apiFetch=(url,options={})=>{const headers={...options.headers};if(authState.session?.access_token)headers.authorization=`Bearer ${authState.session.access_token}`;return fetch(url,{...options,headers})};
if(authState.mode!=='production'||!cfg.supabaseUrl||!cfg.supabasePublishableKey){window.dispatchEvent(new CustomEvent('autozap-authenticated',{detail:{demo:true}}))}else{startAuth()}
async function startAuth(){const saved=localStorage.getItem('autozap-session');if(saved){try{authState.session=JSON.parse(saved);if(await validateSession()){await finishLogin();return}}catch{}localStorage.removeItem('autozap-session')}showAuth()}
async function validateSession(){const r=await fetch(`${cfg.supabaseUrl}/auth/v1/user`,{headers:{apikey:cfg.supabasePublishableKey,authorization:`Bearer ${authState.session.access_token}`}});return r.ok}
function authShell(content){let root=document.querySelector('#auth-root');if(!root){root=document.createElement('div');root.id='auth-root';document.body.appendChild(root)}root.innerHTML=`<div class="auth-screen"><section class="auth-card"><div class="auth-brand"><span>A</span><strong>AutoZap</strong></div>${content}</section></div>`}
function showAuth(message=''){authShell(`<h1>Entrar</h1><p>Gerencie seus dispositivos e integrações.</p>${message?`<div class="auth-message">${message}</div>`:''}<form id="login-form"><label>E-mail</label><input class="input" type="email" name="email" required><label>Senha</label><input class="input" type="password" name="password" minlength="8" required><button class="btn primary">Entrar</button></form><button class="auth-link" id="show-register">Criar minha conta</button>`);document.querySelector('#login-form').onsubmit=login;document.querySelector('#show-register').onclick=showRegister}
function showRegister(){authShell(`<h1>Criar conta</h1><p>Comece seu período de avaliação.</p><form id="register-form"><label>Nome</label><input class="input" name="fullName" required><label>Empresa</label><input class="input" name="companyName" required><label>E-mail</label><input class="input" type="email" name="email" required><label>Senha</label><input class="input" type="password" name="password" minlength="8" required><button class="btn primary">Criar conta</button></form><button class="auth-link" id="show-login">Já tenho uma conta</button>`);document.querySelector('#register-form').onsubmit=register;document.querySelector('#show-login').onclick=()=>showAuth()}
async function login(e){e.preventDefault();const f=new FormData(e.currentTarget),button=e.currentTarget.querySelector('button');button.disabled=true;button.textContent='Entrando…';const r=await fetch(`${cfg.supabaseUrl}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:cfg.supabasePublishableKey,'content-type':'application/json'},body:JSON.stringify({email:f.get('email'),password:f.get('password')})});const data=await r.json();if(!r.ok){showAuth('E-mail ou senha inválidos.');return}authState.session=data;localStorage.setItem('autozap-session',JSON.stringify(data));await finishLogin()}
async function register(e){e.preventDefault();const f=new FormData(e.currentTarget),button=e.currentTarget.querySelector('button');button.disabled=true;button.textContent='Criando…';const r=await fetch(`${cfg.supabaseUrl}/auth/v1/signup`,{method:'POST',headers:{apikey:cfg.supabasePublishableKey,'content-type':'application/json'},body:JSON.stringify({email:f.get('email'),password:f.get('password')})});const data=await r.json();if(!r.ok){showAuth(data.msg||data.error_description||'Não foi possível criar a conta.');return}if(!data.access_token){showAuth('Conta criada. Confirme o e-mail e depois faça login.');return}authState.session=data;localStorage.setItem('autozap-session',JSON.stringify(data));showOnboarding(String(f.get('fullName')),String(f.get('companyName')))}
function showOnboarding(fullName='',companyName=''){authShell(`<h1>Configurar operação</h1><p>Criaremos um ambiente isolado para sua empresa.</p><form id="onboarding-form"><label>Seu nome</label><input class="input" name="fullName" value="${escapeHtml(fullName)}" required><label>Nome da empresa</label><input class="input" name="companyName" value="${escapeHtml(companyName)}" required><button class="btn primary">Concluir configuração</button></form>`);document.querySelector('#onboarding-form').onsubmit=onboarding}
async function onboarding(e){e.preventDefault();const f=new FormData(e.currentTarget),button=e.currentTarget.querySelector('button');button.disabled=true;button.textContent='Configurando…';const r=await window.apiFetch('/api/onboarding',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({fullName:f.get('fullName'),companyName:f.get('companyName')})});const data=await r.json();if(!r.ok){button.disabled=false;button.textContent='Tentar novamente';return}await finishLogin()}
async function finishLogin(){const check=await window.apiFetch('/api/devices');if(check.status===409){showOnboarding();return}document.querySelector('#auth-root')?.remove();window.dispatchEvent(new CustomEvent('autozap-authenticated',{detail:{demo:false}}))}
function escapeHtml(v){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
window.signOut=()=>{localStorage.removeItem('autozap-session');location.reload()};
